# Build, increment patch number and publish
patch:
  rm -dr dist || :
  yarn run build
  yarn version --patch
  @just copy
  cd dist && npm publish

copy:
  cp package.json dist
  cp tsconfig.json dist
  cp README.md dist

# Install a package as both --dev and --peer
extra PACKAGE:
  yarn add --peer {{PACKAGE}} && yarn add --dev {{PACKAGE}}